version: "3.7"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### NGINX Server #########################################
  app:
    container_name: xcrawler-app
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
      - mysql
    links:
      - php-fpm
      - mysql
    networks:
      - frontend
      - backend

  ### PHP-FPM ##############################################
  php-fpm:
    container_name: xcrawler-php
    build:
      context: ./php-fpm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
      - ./logs/cron/:/var/log/cron
      - ./logs/supervisor/:/var/log/supervisord
    expose:
      - "9000"
    networks:
      - backend
    links:
      - mysql

  ### MySQL ################################################
  mysql:
    container_name: xcrawler-mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
      - frontend

  ### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: xcrawler-pma
    build: ./phpmyadmin
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=${MYSQL_PORT}
      - PMA_HOST=mysql
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  ### Redis ###########################################
  redis:
    container_name: xcrawler-redis
    build: ./redis
    volumes:
      - ./data/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
      - frontend
    env_file:
      - .env

  ### RedisAdmin ###########################################
  redisadmin:
    container_name: xcrawler-redisadmin
    image: marian/rebrow:latest
    networks:
      - frontend
      - backend
    ports:
      - "${REDIS_WEBUI_PORT}:5001"
    depends_on:
      - redis

  ### MailDev ###########################################
  maildev:
    container_name: xcrawler-mail
    image: djfarrelly/maildev
    ports:
      - "${MAILDEV_HTTP_PORT}:80"
      - "${MAILDEV_SMTP_PORT}:25"
    networks:
      - frontend
      - backend

  ### Mongo ###########################################
  mongo:
    container_name: xcrawler-mongo
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - frontend
      - backend

  ### Mongo Express ###########################################
  mongo-express:
    container_name: xcrawler-mongoexpress
    image: mongo-express:0.54
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    depends_on:
      - mongo
    networks:
      - frontend
      - backend
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
