name: XCrawler - Build & Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # Test on Tester-01
    runs-on: [ tester-1 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint
        run: composer lint

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: xcrawler_tests
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          mysql -uroot -proot -e "DROP DATABASE IF EXISTS xcrawler_tests; CREATE DATABASE xcrawler_tests;"
          php artisan migrate
          composer test-coverage

      - name: Staging
        if: success()
        run: ~/deployer.sh -s

  # Deploy on Worker-01
  workstation:
    runs-on: [ X64 ]
    steps:
      - uses: actions/checkout@v2
        if: success()

      - name: Setup PHP with coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: pcov

      - name: setup application
        if: success()
        run: |
          sudo service mysql start
          cp .env.testing.example .env.testing
          cp .env.testing.example .env # this is necessary to make `composer install` work with autodiscovery
          mysql -uroot -proot -e "DROP DATABASE IF EXISTS xcrawler_tests; CREATE DATABASE xcrawler_tests;"
          composer install --no-interaction
          php artisan --env=testing key:generate
          php artisan route:cache
          mkdir -p storage/logs && touch storage/logs/laravel.log
          touch coverage.xml # since we always() upload let's make sure the file exists even if we don't run the tests

      - name: lint
        if: success()
        run: |
          ./skip-tests || composer lint


  # Deploy on Worker-01
  deploy:
    runs-on: [ worker-1 ]
    steps:
      - name: Deploy
        if: github.event_name == 'push' && success()
        run: |
          ~/deployer.sh -s
