name: XCrawler - Build & Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # Test on Tester-01
    runs-on: [ tester-1 ]
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: composer lint

      - name: Setup application
        run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        touch coverage.xml # since we always() upload let's make sure the file exists even if we don't run the tests
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        if: success()
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: xcrawler_tests
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          mysql -uroot -proot -e "DROP DATABASE IF EXISTS xcrawler_tests; CREATE DATABASE xcrawler_tests;"
          php artisan migrate
          composer test-coverage

      - name: Coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: coverage.xml
