name: XCrawler - Staging

on:
  push:
    branches: [ develop ]

jobs:
  build:
    # Test on Tester-01
    runs-on: [ tester-1 ]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy on STAG
        run: ~/deployer.sh -s
