name: XCrawler - Deploy Staging

on:
  push:
    branches: [ master ]

jobs:
  # Deploy on Staging
  stagin:
    runs-on: [ X64 ]
    steps:
      - uses: actions/checkout@v2
        if: success()

      - name: Setup PHP with coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: pcov

      - name: setup application
        if: success()
        run: |
          sudo service mysql start
          cp .env.testing.example .env.testing
          cp .env.testing.example .env # this is necessary to make `composer install` work with autodiscovery
          mysql -uroot -proot -e "DROP DATABASE IF EXISTS xcrawler_tests; CREATE DATABASE xcrawler_tests;"
          composer install --no-interaction
          php artisan --env=testing key:generate
          php artisan route:cache
          mkdir -p storage/logs && touch storage/logs/laravel.log
          touch coverage.xml # since we always() upload let's make sure the file exists even if we don't run the tests

      - name: lint
        if: success()
        run: |
          ./skip-tests || composer lint
